 100 ' Simple terminal program in SuperBASIC for the
 105 ' Wildbits/K2 and JR2 Retro computers.         
 110 ' It sends AT commands to the WizNET WiFi      
 115 ' module and displays the responses.           


 120 WIZ_CTRL = $dd80    'Sets the control register for the terminal interface
 125 WIZ_DATA = $dd81    'data in and out to the WizNET module                
 130 WIZ_FIFO = $dd82    'status register to check stack     
 135 stackread = $7800                 
 140 stack = $b0
 145 stackread = $b2
 150 read_buffer = alloc(40)

 155 print chr$(144) 'set background to black
 160 print chr$(131) 'set foreground to green
 165 cls

 170 mlcode(read_buffer)    'assembly for reading from the WizNET FIFO

 175 pokew stack,$7800
 180 pokew stackread,$7800
 185 poke $b5,0          'reset the state machine for parsing IPD
 190 pokew $b6,0         'reset the payload length counter
 195 poke WIZ_CTRL,$00   'Initialize the WizNET control register

 200 initialize(stackread,read_buffer)    ' initialize the WizNET module
 205 connect()       ' Connect to the WiFi network
 210 'server()        ' Connect to the server


 215 ' The terminal interface is active. We are looping and checking for 
 220 ' data from Wiznet as well as the keyboard. $680 is the keyboard
 225 ' status register.
 230 repeat
 235     clcon=0
 240     repeat
 245         call read_buffer
 250         if peekw(stackread) <> peekw(stack) then readterm()
 255         if peek($680)<>0 
 260             k=inkey()
 265             if k=129
 270                 disconnect()
 275             else
 280                 sendkeyboard(k)
 285             endif
 290         endif
 295         clcon=clcon+1
 300     until clcon=100
 305     readstack()
 310     checkresponse()
 315 until peek($b4)=4
 320 print "Connection closed by server"
 325 end

 330 proc sendkeyboard(k)
 335     ' Send the AT command to prepare for sending data to the server
 340     ' wait for the prompt '>' from the WizNET module, then send the
 345     ' key that was pressed on the keyboard to the server.
 350     send$="AT+CIPSEND=1"+chr$(13)+chr$(10)
 355     for s=1 to len(send$)
 360         poke WIZ_DATA,asc(mid$(send$,s,1))
 365     next

 370     ' Wait for the CIPSEND prompt using the ring buffer.
 375     resp=0
 380     while resp<>62
 385         call read_buffer
 390         if peekw($b2) <> peekw($b0)
 395             resp=peek(peekw($b2))
 400             pokew $b2, peekw($b2)+1
 405             if peekw($b2)>=$7fff then pokew $b2,$7800
 410         endif
 415     wend  

 420     ' Send the key payload byte.
 425     poke WIZ_DATA,k

 430     ' Suppress local chip status chatter (Recv and SEND OK).
 435     tag$="SEND OK"
 440     idx=1
 445     done=0
 450     guard=0
 455     while done=0
 460         call read_buffer
 465         if peekw($b2) <> peekw($b0)
 470             c=peek(peekw($b2))
 475             pokew $b2, peekw($b2)+1
 480             if peekw($b2)>=$7fff then pokew $b2,$7800

 485             if c=asc(mid$(tag$,idx,1))
 490                 idx=idx+1
 495                 if idx>len(tag$) then done=1
 500             else
 505                 if c=asc(mid$(tag$,1,1))
 510                     idx=2
 515                 else
 520                     idx=1
 525                 endif
 530             endif
 535         endif

 540         guard=guard+1
 545         if guard>20000 then done=1
 550     wend

 555     ' Drop trailing CR/LF bytes generated by local send acknowledgement.
 560     trimdone=0
 565     trimguard=0
 570     while trimdone=0
 575         call read_buffer
 580         if peekw($b2) <> peekw($b0)
 585             c=peek(peekw($b2))
 590             if c=13
 595                 pokew $b2, peekw($b2)+1
 600                 if peekw($b2)>=$7fff then pokew $b2,$7800
 605             else
 610                 if c=10
 615                     pokew $b2, peekw($b2)+1
 620                     if peekw($b2)>=$7fff then pokew $b2,$7800
 625                 else
 630                     trimdone=1
 635                 endif
 640             endif
 645         else
 650             trimdone=1
 655         endif
 660         trimguard=trimguard+1
 665         if trimguard>64 then trimdone=1
 670     wend
 675 endproc
 680 '
 685 proc initialize(stackread,read_buffer)
 690     ' intialize the terminal by sending the AT commands from the 
 695     ' data statements drop down to the terminal once the commands
 700     ' have been sent. There is no error handling in this code.   
 705     repeat
 710         read a$
 715         if a$<>"stop"
 720             sendcommand(a$)
 725             for n=0 to 10000:next
 730             call read_buffer
 735             readstack()
 740             checkresponse()
 745         endif
 750     until a$="stop"
 755 endproc
 760 '
 765 proc sendcommand(a$)
 770     ' Send an AT command to the WizNET module by writing
 775     ' each character to the WIZ_DATA register, followed 
 780     ' by a carriage return and line feed.
 785     for n=1 to len(a$)
 790         b=asc(mid$(a$,n,1))
 795         if b=39 then b=34
 800         poke WIZ_DATA,b
 805     next
 810     poke WIZ_DATA,$0d
 815     poke WIZ_DATA,$0a
 820 endproc
 825 '
 830 proc checkresponse()
 835     ' Check the response from the WizNET module after
 840     ' sending each AT command         
 845     check=peekw($b0)  
 850     rsp$=""  
 855     for n=check-10 to check-1
 860         rsp$=rsp$+chr$(peek(n))
 865     next
 870     if mid$(rsp$,7,2)="OK" then poke $b4,1
 875     if mid$(rsp$,4,5)="ERROR" then poke $b4,2
 880     if mid$(rsp$,5,4)="FAIL" then poke $b4,3
 885     if mid$(rsp$,3,6)="CLOSED" then poke $b4,4
 890 endproc
 895 '
 900 proc connect()
 905     ' Connect to the WiFi network by sending the appropriate
 910     ' AT commands to the WizNET module. The code waits for a
 915     ' response after each command and checks if the connection
 920     ' was successful.
 925     read a$
 930     sendcommand(a$)
 935     for n=0 to 5000:next
 940     call read_buffer
 945     readstack()
 950     poke $b4,0
 955     while peek($b4)<>1
 960         for n=0 to 20000:next
 965         call read_buffer
 970         readstack()
 975         checkresponse()
 980         if peek($b4)=3 
 985             print "Failed to connect to WiFi network"
 990             stop
 995         endif
1000     wend
1005     read a$
1010     sendcommand(a$)
1015     for n=0 to 20000:next
1020     call read_buffer
1025     readstack()
1030     read a$
1035     sendcommand(a$)
1040     for n=0 to 20000:next
1045     call read_buffer
1050 endproc 
1055 '
1060 proc readstack()
1065     while peekw($b2) <> peekw($b0) 
1070         readterm()
1075     wend
1080 endproc
1085 '
1090 proc readone()
1095     print chr$(peek(peekw($b2)));
1100     pokew $b2, peekw($b2)+1
1105     if peekw($b2)>=$7fff then pokew $b2,$7800
1110 endproc
1115 '
1120 proc readterm()
1125     t$= chr$(peek(peekw($b2)))
1130     checkipd()
1135     pokew $b2, peekw($b2)+1
1140     if peekw($b2)>=$7fff then pokew $b2,$7800
1145 endproc
1150 '
1155 proc printpayload()
1160     for n=1 to peek($b6)
1165         readone()
1170     next
1175 endproc
1180 '
1185 proc checkipd()
1190     st=peek($b5)
1195     rm=peekw($b6)
1200     handled=0

1205     if (st=0) & (handled=0)
1210         if t$="+"
1215             poke $b5,1
1220         else
1225             print t$;
1230         endif
1235         handled=1
1240     endif

1245     if (st=1) & (handled=0)
1250         if t$="I"
1255             poke $b5,2
1260         else
1265             print "+";
1270             if t$="+"
1275                 poke $b5,1
1280             else
1285                 print t$;
1290                 poke $b5,0
1295             endif
1300         endif
1305         handled=1
1310     endif

1315     if (st=2) & (handled=0)
1320         if t$="P"
1325             poke $b5,3
1330         else
1335             print "+I";
1340             if t$="+"
1345                 poke $b5,1
1350             else
1355                 print t$;
1360                 poke $b5,0
1365             endif
1370         endif
1375         handled=1
1380     endif

1385     if (st=3) & (handled=0)
1390         if t$="D"
1395             poke $b5,4
1400         else
1405             print "+IP";
1410             if t$="+"
1415                 poke $b5,1
1420             else
1425                 print t$;
1430                 poke $b5,0
1435             endif
1440         endif
1445         handled=1
1450     endif

1455     if (st=4) & (handled=0)
1460         if t$=","
1465             pokew $b6,0
1470             poke $b5,5
1475         else
1480             print "+IPD";
1485             if t$="+"
1490                 poke $b5,1
1495             else
1500                 print t$;
1505                 poke $b5,0
1510             endif
1515         endif
1520         handled=1
1525     endif

1530     if (st=5) & (handled=0)
1535         ch=asc(t$)
1540         if (ch>=48) & (ch<=57)
1545             rm=(rm*10)+(ch-48)
1550             pokew $b6,rm
1555         else
1560             if (t$=":") & (rm>0)
1565                 poke $b5,6
1570             else
1575                 print "+IPD,";
1580                 print str$(rm);
1585                 print t$;
1590                 poke $b5,0
1595                 pokew $b6,0
1600             endif
1605         endif
1610         handled=1
1615     endif

1620     if (st=6) & (handled=0)
1625         print t$;
1630         rm=rm-1
1635         pokew $b6,rm
1640         if rm<=0
1645             poke $b5,0
1650             pokew $b6,0
1655         endif
1660         handled=1
1665     endif

1670     if handled=0
1675         poke $b5,0
1680         pokew $b6,0
1685         print t$;
1690     endif
1695 endproc
1700 '
1705 proc disconnect()
1710     ' Send the AT command to disconnect from the server, and then
1715     ' reset the WizNET module.
1720     send$="AT+CIPCLOSE"+chr$(13)+chr$(10)
1725     for s=1 to len(send$)
1730         poke WIZ_DATA,asc(mid$(send$,s,1))
1735     next
1740     readstack()
1745     for n=0 to 20000:next
1750     send$="AT+RST"+chr$(13)+chr$(10)
1755     for s=1 to len(send$)
1760         poke WIZ_DATA,asc(mid$(send$,s,1))
1765     next
1770     readstack()
1775 endproc
1780 '
1785 proc mlcode(read_buffer)
1790     for pass=0 to 1
1795         assemble read_buffer,pass
1800         ' Check if there is data in the FIFO           
1805         ' If there is, read and store it in the buffer,
1810         ' and update the buffer pointer.               
1815         ' if no datais available, return to BASIC.     
1820         .start
1825             lda $dd82          'Wiznet FIFO status register
1830             bne read_wiznet 
1835             rts     
1840         'read a byte from the FIFO and store it in the buffer
1845         .read_wiznet
1850             lda $dd81          'Wiznet data register
1855             sta ($b0)         
1860         'incrment the buffer pointer
1865             clc              
1870             lda $b0
1875             adc #$01
1880             sta $b0
1885             lda $b1
1890             adc #$00
1895             sta $b1            
1900         ' compair pointer to the end of the buffer              
1905         ' and reset to the beginning if we have reached the end.
1910             cmp #$80           
1915             bcc start                    
1920             stz $b0
1925             lda #$78
1930             sta $b1
1935             bra start        
1940     next
1945 endproc
1950 '
1955 ' initialize the WizNET chip with these AT commands
1960 data "AT+GMR"
1965 data "AT+UART_CUR?"
1970 data "AT+CWMODE_CUR=1"
1975 data "AT+CWMODE_CUR?"
1980 data "AT+CIPMUX=0"
1985 data "stop"

1990 ' connect to the wifi network
1995 data "AT+CWJAP_CUR='Defiance','CorvairCorsa'"
2000 data "AT+CIPSTA_CUR?"

2005 ' connect to the server
2010 data "AT+CIPSTART='TCP','192.168.17.54',8119"
