' Simple terminal program in SuperBASIC for the
' Wildbits/K2 and JR2 Retro computers.         
' It sends AT commands to the WizNET WiFi      
' module and displays the responses.           


WIZ_CTRL = $dd80    'Sets the control register for the terminal interface
WIZ_DATA = $dd81    'data in and out to the WizNET module                
WIZ_FIFO = $dd82    'status register to check stack     
stackread = $7800                 
stack = $b0
stackread = $b2
read_buffer = alloc(40)
send_key = alloc(72)

print chr$(144) 'set background to black
print chr$(131) 'set foreground to green
cls

mlcode(read_buffer)    'assembly for reading from the WizNET FIFO
sendmlcode(send_key)          'assembly for sending keyboard input to the WizNET module

pokew stack,$7800
pokew stackread,$7800
poke $b5,0          'reset the state machine for parsing IPD
pokew $b6,0         'reset the payload length counter
poke WIZ_CTRL,$00   'Initialize the WizNET control register

initialize(stackread,read_buffer)    ' initialize the WizNET module
connect()       ' Connect to the WiFi network
'server()        ' Connect to the server


' The terminal interface is active. We are looping and checking for 
' data from Wiznet as well as the keyboard. $680 is the keyboard
' status register.
repeat
    clcon=0
    repeat
        call read_buffer
        if peekw(stackread) <> peekw(stack) then readterm()
        if peek($680)<>0 
            k=inkey()
            if k=129
                disconnect()
            else
                sendkeyboard()
            endif
        endif
        clcon=clcon+1
    until clcon=100
    readstack()
    checkresponse()
until peek($b4)=4
print "Connection closed by server"
end

proc sendkeyboard()
    ' send the wizNET send command and wait for the > prompt
    ' then send the keyboard input to the WizNET module. 
    call send_key
    ' Suppress local chip status chatter (Recv and SEND OK).
    tag$="SEND OK"
    idx=1
    done=0
    guard=0
    while done=0
        call read_buffer
        if peekw($b2) <> peekw($b0)
            c=peek(peekw($b2))
            pokew $b2, peekw($b2)+1
            if peekw($b2)>=$7fff then pokew $b2,$7800

            if c=asc(mid$(tag$,idx,1))
                idx=idx+1
                if idx>len(tag$) then done=1
            else
                if c=asc(mid$(tag$,1,1))
                    idx=2
                else
                    idx=1
                endif
            endif
        endif

        guard=guard+1
        if guard>20000 then done=1
    wend

    ' Drop trailing CR/LF bytes generated by local send acknowledgement.
    trimdone=0
    trimguard=0
    while trimdone=0
        call read_buffer
        if peekw($b2) <> peekw($b0)
            c=peek(peekw($b2))
            if c=13
                pokew $b2, peekw($b2)+1
                if peekw($b2)>=$7fff then pokew $b2,$7800
            else
                if c=10
                    pokew $b2, peekw($b2)+1
                    if peekw($b2)>=$7fff then pokew $b2,$7800
                else
                    trimdone=1
                endif
            endif
        else
            trimdone=1
        endif
        trimguard=trimguard+1
        if trimguard>64 then trimdone=1
    wend
endproc

proc initialize(stackread,read_buffer)
    ' setup up memory for keyboard send. 
    ' store sting starting at $c0 and then use the assembly
    ' routine to send it to the WizNET module.
    send$="AT+CIPSEND=1"+chr$(13)+chr$(10)
    for s=1 to len(send$)
        poke $bf+s,asc(mid$(send$,s,1))
    next
    ' intialize the terminal by sending the AT commands from the 
    ' data statements drop down to the terminal once the commands
    ' have been sent. There is no error handling in this code.   
    repeat
        read a$
        if a$<>"stop"
            sendcommand(a$)
            for n=0 to 10000:next
            call read_buffer
            readstack()
            checkresponse()
        endif
    until a$="stop"
endproc

proc sendcommand(a$)
    ' Send an AT command to the WizNET module by writing
    ' each character to the WIZ_DATA register, followed 
    ' by a carriage return and line feed.
    for n=1 to len(a$)
        b=asc(mid$(a$,n,1))
        if b=39 then b=34
        poke WIZ_DATA,b
    next
    poke WIZ_DATA,$0d
    poke WIZ_DATA,$0a
endproc

proc checkresponse()
    ' Check the response from the WizNET module after
    ' sending each AT command         
    check=peekw($b0)  
    rsp$=""  
    for n=check-10 to check-1
        rsp$=rsp$+chr$(peek(n))
    next
    if mid$(rsp$,7,2)="OK" then poke $b4,1
    if mid$(rsp$,4,5)="ERROR" then poke $b4,2
    if mid$(rsp$,5,4)="FAIL" then poke $b4,3
    if mid$(rsp$,3,6)="CLOSED" then poke $b4,4
endproc

proc connect()
    ' Connect to the WiFi network by sending the appropriate
    ' AT commands to the WizNET module. The code waits for a
    ' response after each command and checks if the connection
    ' was successful.
    read a$
    sendcommand(a$)
    for n=0 to 5000:next
    call read_buffer
    readstack()
    poke $b4,0
    while peek($b4)<>1
        for n=0 to 20000:next
        call read_buffer
        readstack()
        checkresponse()
        if peek($b4)=3 
            print "Failed to connect to WiFi network"
            stop
        endif
    wend
    read a$
    sendcommand(a$)
    for n=0 to 20000:next
    call read_buffer
    readstack()
    read a$
    sendcommand(a$)
    for n=0 to 20000:next
    call read_buffer
endproc 

proc readstack()
    while peekw($b2) <> peekw($b0) 
        readterm()
    wend
endproc

proc readone()
    print chr$(peek(peekw($b2)));
    pokew $b2, peekw($b2)+1
    if peekw($b2)>=$7fff then pokew $b2,$7800
endproc

proc readterm()
    t$= chr$(peek(peekw($b2)))
    st=peek($b5)
    if st=6
        print t$;
        rm=peekw($b6)-1
        pokew $b6,rm
        if rm<=0
            poke $b5,0
            pokew $b6,0
        endif
    else
        checkipd()
    endif
    pokew $b2, peekw($b2)+1
    if peekw($b2)>=$7fff then pokew $b2,$7800
endproc

proc printpayload()
    for n=1 to peek($b6)
        readone()
    next
endproc

proc checkipd()
    st=peek($b5)
    rm=peekw($b6)
    handled=0

    if (st=0) & (handled=0)
        if t$="+"
            poke $b5,1
        else
            print t$;
        endif
        handled=1
    endif

    if (st=1) & (handled=0)
        if t$="I"
            poke $b5,2
        else
            print "+";
            if t$="+"
                poke $b5,1
            else
                print t$;
                poke $b5,0
            endif
        endif
        handled=1
    endif

    if (st=2) & (handled=0)
        if t$="P"
            poke $b5,3
        else
            print "+I";
            if t$="+"
                poke $b5,1
            else
                print t$;
                poke $b5,0
            endif
        endif
        handled=1
    endif

    if (st=3) & (handled=0)
        if t$="D"
            poke $b5,4
        else
            print "+IP";
            if t$="+"
                poke $b5,1
            else
                print t$;
                poke $b5,0
            endif
        endif
        handled=1
    endif

    if (st=4) & (handled=0)
        if t$=","
            pokew $b6,0
            poke $b5,5
        else
            print "+IPD";
            if t$="+"
                poke $b5,1
            else
                print t$;
                poke $b5,0
            endif
        endif
        handled=1
    endif

    if (st=5) & (handled=0)
        ch=asc(t$)
        if (ch>=48) & (ch<=57)
            rm=(rm*10)+(ch-48)
            pokew $b6,rm
        else
            if (t$=":") & (rm>0)
                poke $b5,6
            else
                print "+IPD,";
                print str$(rm);
                print t$;
                poke $b5,0
                pokew $b6,0
            endif
        endif
        handled=1
    endif

    if (st=6) & (handled=0)
        print t$;
        rm=rm-1
        pokew $b6,rm
        if rm<=0
            poke $b5,0
            pokew $b6,0
        endif
        handled=1
    endif

    if handled=0
        poke $b5,0
        pokew $b6,0
        print t$;
    endif
endproc

proc disconnect()
    ' Send the AT command to disconnect from the server, and then
    ' reset the WizNET module.
    send$="AT+CIPCLOSE"+chr$(13)+chr$(10)
    for s=1 to len(send$)
        poke WIZ_DATA,asc(mid$(send$,s,1))
    next
    readstack()
    for n=0 to 20000:next
    send$="AT+RST"+chr$(13)+chr$(10)
    for s=1 to len(send$)
        poke WIZ_DATA,asc(mid$(send$,s,1))
    next
    readstack()
endproc

proc sendmlcode(send_key)
    for pass=0 to 1
        assemble send_key,pass
        .st
        ' grab that key from the buffer to send to the 
        ' wiznet module, and then return to BASIC.
            stz $680
            ldx #$00
        .loopx
            lda ($c0),x
            sta WIZ_DATA
            inx
            cpx #$0e
            bcc loopx
        .wait
            jsr read_buffer
            lda $b1
            cmp $b3
            beq chklo
            bra chkforprompt
        .chklo
            lda $b0
            cmp $b2
            beq wait
        .chkforprompt
            lda ($b2)
            cmp #62
            beq send_key
        .nextchar
            clc
            lda $b2
            adc #1
            sta $b2
            lda $b3
            adc #0
            sta $b3
            cmp #$80
            bcc wait
            stz $b2
            lda #$78
            sta $b3
            bra wait
        .send_key
            lda $678
            sta WIZ_DATA
            rts
    next
endproc


        
proc mlcode(read_buffer)
    for pass=0 to 1
        assemble read_buffer,pass
        ' Check if there is data in the FIFO           
        ' If there is, read and store it in the buffer,
        ' and update the buffer pointer.               
        ' if no datais available, return to BASIC.     
        .start
            lda $dd82          'Wiznet FIFO status register
            bne read_wiznet 
            rts     
        'read a byte from the FIFO and store it in the buffer
        .read_wiznet
            lda $dd81          'Wiznet data register
            sta ($b0)         
        'incrment the buffer pointer
            clc              
            lda $b0
            adc #$01
            sta $b0
            lda $b1
            adc #$00
            sta $b1            
        ' compair pointer to the end of the buffer              
        ' and reset to the beginning if we have reached the end.
            cmp #$80           
            bcc start                    
            stz $b0
            lda #$78
            sta $b1
            bra start        
    next
endproc

' initialize the WizNET chip with these AT commands
data "AT+GMR"
data "AT+UART_CUR?"
data "AT+CWMODE_CUR=1"
data "AT+CWMODE_CUR?"
data "AT+CIPMUX=0"
data "stop"

' connect to the wifi network
data "AT+CWJAP_CUR='SSID','PASSWORD'"
data "AT+CIPSTA_CUR?"

' connect to the server
data "AT+CIPSTART='TCP','192.168.17.54',8119"
