 100 ' Simple terminal program in SuperBASIC for the
 105 ' Wildbits/K2 and JR2 Retro computers.         
 110 ' It sends AT commands to the WizNET WiFi      
 115 ' module and displays the responses.           


 120 WIZ_CTRL = $dd80    'Sets the control register for the terminal interface
 125 WIZ_DATA = $dd81    'data in and out to the WizNET module                
 130 WIZ_FIFO = $dd82    'status register to check stack     
 135 stackread = $7800                 
 140 stack = $b0
 145 stackread = $b2
 150 read_buffer = alloc(40)
 155 send_key = alloc(72)

 160 print chr$(144) 'set background to black
 165 print chr$(131) 'set foreground to green
 170 cls

 175 mlcode(read_buffer)    'assembly for reading from the WizNET FIFO
 180 sendmlcode(send_key)          'assembly for sending keyboard input to the WizNET module

 185 pokew stack,$7800
 190 pokew stackread,$7800
 195 poke $b5,0          'reset the state machine for parsing IPD
 200 pokew $b6,0         'reset the payload length counter
 205 poke WIZ_CTRL,$00   'Initialize the WizNET control register

 210 initialize(stackread,read_buffer)    ' initialize the WizNET module
 215 connect()       ' Connect to the WiFi network
 220 'server()        ' Connect to the server


 225 ' The terminal interface is active. We are looping and checking for 
 230 ' data from Wiznet as well as the keyboard. $680 is the keyboard
 235 ' status register.
 240 repeat
 245     clcon=0
 250     repeat
 255         call read_buffer
 260         if peekw(stackread) <> peekw(stack) then readterm()
 265         if peek($680)<>0 
 270             k=inkey()
 275             if k=129
 280                 disconnect()
 285             else
 290                 sendkeyboard()
 295             endif
 300         endif
 305         clcon=clcon+1
 310     until clcon=100
 315     readstack()
 320     checkresponse()
 325 until peek($b4)=4
 330 print "Connection closed by server"
 335 end

 340 proc sendkeyboard()
 345     ' send the wizNET send command and wait for the > prompt
 350     ' then send the keyboard input to the WizNET module. 
 355     call send_key
 360     ' Suppress local chip status chatter (Recv and SEND OK).
 365     tag$="SEND OK"
 370     idx=1
 375     done=0
 380     guard=0
 385     while done=0
 390         call read_buffer
 395         if peekw($b2) <> peekw($b0)
 400             c=peek(peekw($b2))
 405             pokew $b2, peekw($b2)+1
 410             if peekw($b2)>=$7fff then pokew $b2,$7800

 415             if c=asc(mid$(tag$,idx,1))
 420                 idx=idx+1
 425                 if idx>len(tag$) then done=1
 430             else
 435                 if c=asc(mid$(tag$,1,1))
 440                     idx=2
 445                 else
 450                     idx=1
 455                 endif
 460             endif
 465         endif

 470         guard=guard+1
 475         if guard>20000 then done=1
 480     wend

 485     ' Drop trailing CR/LF bytes generated by local send acknowledgement.
 490     trimdone=0
 495     trimguard=0
 500     while trimdone=0
 505         call read_buffer
 510         if peekw($b2) <> peekw($b0)
 515             c=peek(peekw($b2))
 520             if c=13
 525                 pokew $b2, peekw($b2)+1
 530                 if peekw($b2)>=$7fff then pokew $b2,$7800
 535             else
 540                 if c=10
 545                     pokew $b2, peekw($b2)+1
 550                     if peekw($b2)>=$7fff then pokew $b2,$7800
 555                 else
 560                     trimdone=1
 565                 endif
 570             endif
 575         else
 580             trimdone=1
 585         endif
 590         trimguard=trimguard+1
 595         if trimguard>64 then trimdone=1
 600     wend
 605 endproc

 610 proc initialize(stackread,read_buffer)
 615     ' setup up memory for keyboard send. 
 620     ' store sting starting at $c0 and then use the assembly
 625     ' routine to send it to the WizNET module.
 630     send$="AT+CIPSEND=1"+chr$(13)+chr$(10)
 635     for s=1 to len(send$)
 640         poke $bf+s,asc(mid$(send$,s,1))
 645     next
 650     ' intialize the terminal by sending the AT commands from the 
 655     ' data statements drop down to the terminal once the commands
 660     ' have been sent. There is no error handling in this code.   
 665     repeat
 670         read a$
 675         if a$<>"stop"
 680             sendcommand(a$)
 685             for n=0 to 10000:next
 690             call read_buffer
 695             readstack()
 700             checkresponse()
 705         endif
 710     until a$="stop"
 715 endproc

 720 proc sendcommand(a$)
 725     ' Send an AT command to the WizNET module by writing
 730     ' each character to the WIZ_DATA register, followed 
 735     ' by a carriage return and line feed.
 740     for n=1 to len(a$)
 745         b=asc(mid$(a$,n,1))
 750         if b=39 then b=34
 755         poke WIZ_DATA,b
 760     next
 765     poke WIZ_DATA,$0d
 770     poke WIZ_DATA,$0a
 775 endproc

 780 proc checkresponse()
 785     ' Check the response from the WizNET module after
 790     ' sending each AT command         
 795     check=peekw($b0)  
 800     rsp$=""  
 805     for n=check-10 to check-1
 810         rsp$=rsp$+chr$(peek(n))
 815     next
 820     if mid$(rsp$,7,2)="OK" then poke $b4,1
 825     if mid$(rsp$,4,5)="ERROR" then poke $b4,2
 830     if mid$(rsp$,5,4)="FAIL" then poke $b4,3
 835     if mid$(rsp$,3,6)="CLOSED" then poke $b4,4
 840 endproc

 845 proc connect()
 850     ' Connect to the WiFi network by sending the appropriate
 855     ' AT commands to the WizNET module. The code waits for a
 860     ' response after each command and checks if the connection
 865     ' was successful.
 870     read a$
 875     sendcommand(a$)
 880     for n=0 to 5000:next
 885     call read_buffer
 890     readstack()
 895     poke $b4,0
 900     while peek($b4)<>1
 905         for n=0 to 20000:next
 910         call read_buffer
 915         readstack()
 920         checkresponse()
 925         if peek($b4)=3 
 930             print "Failed to connect to WiFi network"
 935             stop
 940         endif
 945     wend
 950     read a$
 955     sendcommand(a$)
 960     for n=0 to 20000:next
 965     call read_buffer
 970     readstack()
 975     read a$
 980     sendcommand(a$)
 985     for n=0 to 20000:next
 990     call read_buffer
 995 endproc 

1000 proc readstack()
1005     while peekw($b2) <> peekw($b0) 
1010         readterm()
1015     wend
1020 endproc

1025 proc readone()
1030     print chr$(peek(peekw($b2)));
1035     pokew $b2, peekw($b2)+1
1040     if peekw($b2)>=$7fff then pokew $b2,$7800
1045 endproc

1050 proc readterm()
1055     t$= chr$(peek(peekw($b2)))
1060     st=peek($b5)
1065     if st=6
1070         print t$;
1075         rm=peekw($b6)-1
1080         pokew $b6,rm
1085         if rm<=0
1090             poke $b5,0
1095             pokew $b6,0
1100         endif
1105     else
1110         checkipd()
1115     endif
1120     pokew $b2, peekw($b2)+1
1125     if peekw($b2)>=$7fff then pokew $b2,$7800
1130 endproc

1135 proc printpayload()
1140     for n=1 to peek($b6)
1145         readone()
1150     next
1155 endproc

1160 proc checkipd()
1165     st=peek($b5)
1170     rm=peekw($b6)
1175     handled=0

1180     if (st=0) & (handled=0)
1185         if t$="+"
1190             poke $b5,1
1195         else
1200             print t$;
1205         endif
1210         handled=1
1215     endif

1220     if (st=1) & (handled=0)
1225         if t$="I"
1230             poke $b5,2
1235         else
1240             print "+";
1245             if t$="+"
1250                 poke $b5,1
1255             else
1260                 print t$;
1265                 poke $b5,0
1270             endif
1275         endif
1280         handled=1
1285     endif

1290     if (st=2) & (handled=0)
1295         if t$="P"
1300             poke $b5,3
1305         else
1310             print "+I";
1315             if t$="+"
1320                 poke $b5,1
1325             else
1330                 print t$;
1335                 poke $b5,0
1340             endif
1345         endif
1350         handled=1
1355     endif

1360     if (st=3) & (handled=0)
1365         if t$="D"
1370             poke $b5,4
1375         else
1380             print "+IP";
1385             if t$="+"
1390                 poke $b5,1
1395             else
1400                 print t$;
1405                 poke $b5,0
1410             endif
1415         endif
1420         handled=1
1425     endif

1430     if (st=4) & (handled=0)
1435         if t$=","
1440             pokew $b6,0
1445             poke $b5,5
1450         else
1455             print "+IPD";
1460             if t$="+"
1465                 poke $b5,1
1470             else
1475                 print t$;
1480                 poke $b5,0
1485             endif
1490         endif
1495         handled=1
1500     endif

1505     if (st=5) & (handled=0)
1510         ch=asc(t$)
1515         if (ch>=48) & (ch<=57)
1520             rm=(rm*10)+(ch-48)
1525             pokew $b6,rm
1530         else
1535             if (t$=":") & (rm>0)
1540                 poke $b5,6
1545             else
1550                 print "+IPD,";
1555                 print str$(rm);
1560                 print t$;
1565                 poke $b5,0
1570                 pokew $b6,0
1575             endif
1580         endif
1585         handled=1
1590     endif

1595     if (st=6) & (handled=0)
1600         print t$;
1605         rm=rm-1
1610         pokew $b6,rm
1615         if rm<=0
1620             poke $b5,0
1625             pokew $b6,0
1630         endif
1635         handled=1
1640     endif

1645     if handled=0
1650         poke $b5,0
1655         pokew $b6,0
1660         print t$;
1665     endif
1670 endproc

1675 proc disconnect()
1680     ' Send the AT command to disconnect from the server, and then
1685     ' reset the WizNET module.
1690     send$="AT+CIPCLOSE"+chr$(13)+chr$(10)
1695     for s=1 to len(send$)
1700         poke WIZ_DATA,asc(mid$(send$,s,1))
1705     next
1710     readstack()
1715     for n=0 to 20000:next
1720     send$="AT+RST"+chr$(13)+chr$(10)
1725     for s=1 to len(send$)
1730         poke WIZ_DATA,asc(mid$(send$,s,1))
1735     next
1740     readstack()
1745 endproc

1750 proc sendmlcode(send_key)
1755     for pass=0 to 1
1760         assemble send_key,pass
1765         .st
1770         ' grab that key from the buffer to send to the 
1775         ' wiznet module, and then return to BASIC.
1780             stz $680
1785             ldx #$00
1790         .loopx
1795             lda ($c0),x
1800             sta WIZ_DATA
1805             inx
1810             cpx #$0e
1815             bcc loopx
1820         .wait
1825             jsr read_buffer
1830             lda $b1
1835             cmp $b3
1840             beq chklo
1845             bra chkforprompt
1850         .chklo
1855             lda $b0
1860             cmp $b2
1865             beq wait
1870         .chkforprompt
1875             lda ($b2)
1880             cmp #62
1885             beq send_key
1890         .nextchar
1895             clc
1900             lda $b2
1905             adc #1
1910             sta $b2
1915             lda $b3
1920             adc #0
1925             sta $b3
1930             cmp #$80
1935             bcc wait
1940             stz $b2
1945             lda #$78
1950             sta $b3
1955             bra wait
1960         .send_key
1965             lda $678
1970             sta WIZ_DATA
1975             rts
1980     next
1985 endproc


        
1990 proc mlcode(read_buffer)
1995     for pass=0 to 1
2000         assemble read_buffer,pass
2005         ' Check if there is data in the FIFO           
2010         ' If there is, read and store it in the buffer,
2015         ' and update the buffer pointer.               
2020         ' if no datais available, return to BASIC.     
2025         .start
2030             lda $dd82          'Wiznet FIFO status register
2035             bne read_wiznet 
2040             rts     
2045         'read a byte from the FIFO and store it in the buffer
2050         .read_wiznet
2055             lda $dd81          'Wiznet data register
2060             sta ($b0)         
2065         'incrment the buffer pointer
2070             clc              
2075             lda $b0
2080             adc #$01
2085             sta $b0
2090             lda $b1
2095             adc #$00
2100             sta $b1            
2105         ' compair pointer to the end of the buffer              
2110         ' and reset to the beginning if we have reached the end.
2115             cmp #$80           
2120             bcc start                    
2125             stz $b0
2130             lda #$78
2135             sta $b1
2140             bra start        
2145     next
2150 endproc

2155 ' initialize the WizNET chip with these AT commands
2160 data "AT+GMR"
2165 data "AT+UART_CUR?"
2170 data "AT+CWMODE_CUR=1"
2175 data "AT+CWMODE_CUR?"
2180 data "AT+CIPMUX=0"
2185 data "stop"

2190 ' connect to the wifi network
2195 data "AT+CWJAP_CUR='SSID','PASSWORD'"
2200 data "AT+CIPSTA_CUR?"

2205 ' connect to the server
2210 data "AT+CIPSTART='TCP','192.168.17.54',8119"
